name: AdvancedVote
main: com.mcdev.advancedvote.bukkit.BukkitPlugin
version: 2.5
author: MCDevTec
api-version: 1.13
description: Plugin avanzado sobre votaciones de 40ServidoresMC!
commands:
    advancedvote:
        description: Comando principal de AdvancedVote
        aliases: [adv]
    vote40:
        description: Comando principal de 40ServidoresMC
        aliases: [votar40, voto40, mivoto40]